name: Test Build
on:
  push:
    branches:
      - "**"
      - "!main"
      - "!staging"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - run: npm install
      - run: npm run build
